#!/usr/bin/env bash
# postStartCommand: runs on every container start. The normal foreground path
# is fast; an already-running OpenCode service gets a bounded MCP registration
# wait after config/credential changes. Syncs env + MCP configs, then refreshes
# CLIs in the background at most once per day (set
# DEVCONTAINER_CLI_REFRESH=always in .env.local to force).
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/env.sh
source "$script_dir/lib/env.sh"
# shellcheck source=lib/install-clis.sh
source "$script_dir/lib/install-clis.sh"
# shellcheck source=lib/mcp-config.sh
source "$script_dir/lib/mcp-config.sh"

devcontainer_fix_ownership

# Recover cleanly if a previous lifecycle command was interrupted or the
# persistent npm volume was reset. Keep the repair paths independent: a missing
# backend launcher must not reinstall every core CLI, and a core npm failure
# must not be hidden by a later successful backend install.
if ! devcontainer_core_clis_ready; then
  echo "[devcontainer] core CLI state is incomplete; repairing it before config sync..."
  devcontainer_install_clis
fi
if ! devcontainer_ai_backends_ready; then
  echo "[devcontainer] AI backend state is incomplete; repairing launchers..."
  bash "$script_dir/../ai-backends.sh" install
fi

# Persist resolved credentials for interactive shells (600, container-only).
env_file="$HOME/.container-env.sh"
devcontainer_assert_no_symlink_path "$env_file"
env_tmp="$(mktemp "${env_file}.XXXXXX")"
trap 'rm -f "$env_tmp"' EXIT
{
  printf '# generated by post-start.sh from .env.local / .env / inherited env\n'
  for name in GITHUB_PERSONAL_ACCESS_TOKEN Z_AI_API_KEY Z_AI_MODE GH_TOKEN OPENAI_API_KEY \
    ANTHROPIC_API_KEY OPENROUTER_API_KEY CONTEXT7_API_KEY CODEX_HOME \
    CODEX_ZAI_MODEL CODEX_ZAI_REASONING_EFFORT CODEX_OPENROUTER_MODEL \
    ZAI_API_TIMEOUT_MS OPENROUTER_API_TIMEOUT_MS \
    CLAUDE_ZAI_SONNET_MODEL CLAUDE_ZAI_OPUS_MODEL CLAUDE_ZAI_HAIKU_MODEL \
    CLAUDE_OPENROUTER_FABLE_MODEL CLAUDE_OPENROUTER_OPUS_MODEL \
    CLAUDE_OPENROUTER_SONNET_MODEL CLAUDE_OPENROUTER_HAIKU_MODEL; do
    value="${!name:-}"
    if [ -n "$value" ]; then
      printf 'export %s=%q\n' "$name" "$value"
    fi
  done
} > "$env_tmp"
env_changed=0
if [ ! -f "$env_file" ] || ! cmp -s "$env_tmp" "$env_file"; then
  devcontainer_assert_no_symlink_path "$env_file"
  mv -f "$env_tmp" "$env_file"
  env_changed=1
else
  rm -f "$env_tmp"
fi
chmod 600 "$env_file" 2>/dev/null || true
for rc in "$HOME/.bashrc" "$HOME/.profile"; do
  if [ -f "$rc" ] && ! grep -q '.container-env.sh' "$rc"; then
    printf '\n[ -f "$HOME/.container-env.sh" ] && . "$HOME/.container-env.sh"\n' >> "$rc"
  fi
done

# OpenCode has several documented global/custom path forms. Hash the effective
# target rather than assuming ~/.config/opencode so a service restart observes
# the same file that the writer updated.
devcontainer_opencode_config_fingerprint() {
  local file
  file="$(devcontainer_opencode_config_file)"
  devcontainer_assert_no_symlink_path "$file" || return 1
  {
    printf '%s\n' "$file"
    if [ -n "${OPENCODE_CONFIG_CONTENT:-}" ]; then
      printf '%s' "$OPENCODE_CONFIG_CONTENT" | sha256sum
    elif [ -f "$file" ]; then
      sha256sum "$file"
    else
      printf 'missing\n'
    fi
  } | sha256sum | cut -d" " -f1
}

devcontainer_opencode_expected_mcp_names() {
  # Only ENABLED servers must appear in `mcp list`: token-gated entries are
  # written `disabled` when their credential is missing, and the list may omit
  # disabled registrations. Keyless servers are always managed and expected.
  if [ -n "${GITHUB_PERSONAL_ACCESS_TOKEN:-}" ]; then
    printf '%s\n' github
  fi
  if [ -n "${Z_AI_API_KEY:-}" ]; then
    printf '%s\n' zai-vision zai-web-search zai-web-reader zai-zread
  fi
  printf '%s\n' microsoft-docs context7
  if command -v uvx >/dev/null 2>&1; then
    printf '%s\n' git
  fi
}

devcontainer_wait_for_opencode_mcp() {
  local output expected name ready
  command -v opencode >/dev/null 2>&1 || return 0
  expected="$(devcontainer_opencode_expected_mcp_names)"
  for _ in 1 2 3 4 5; do
    if output="$(timeout 15s opencode mcp list 2>/dev/null)"; then
      if ! grep -Fxq "No MCP servers configured" <<<"$output"; then
        ready=1
        while IFS= read -r name; do
          [ -n "$name" ] || continue
          # Registration, not network authentication, is the lifecycle gate:
          # test credentials may legitimately show a failed connection. A
          # missing/empty list is never considered ready.
          if ! grep -Eq "(^|[[:space:]])${name}([[:space:]]|$)" <<<"$output"; then
            ready=0
            break
          fi
        done <<<"$expected"
        [ "$ready" -eq 1 ] && return 0
      fi
    fi
    sleep 1
  done
  return 1
}

devcontainer_refresh_opencode_service_if_needed() {
  local changed="$1" status restart_marker
  [ "$changed" -eq 1 ] || return 0
  command -v opencode >/dev/null 2>&1 || return 0
  restart_marker="$(devcontainer_state_dir)/opencode-restart.pending"
  status="$(timeout 10s opencode service status 2>/dev/null || true)"
  [ -n "$status" ] || return 0
  case "${status,,}" in
    *"not running"* | *stopped*) return 0 ;;
    *running* | *started* | *http://* | *https://*) ;;
    *)
      printf '[devcontainer] WARN: could not classify OpenCode service status; leaving it untouched.\n' >&2
      return 0
      ;;
  esac
  if ! timeout 30s opencode service restart >/dev/null 2>&1; then
    mkdir -p "$(devcontainer_state_dir)"
    : > "$restart_marker" 2>/dev/null || true
    printf '[devcontainer] ERROR: OpenCode is running but its service could not be restarted after config/credential changes.\n' >&2
    return 1
  fi
  if ! devcontainer_wait_for_opencode_mcp; then
    # The service is up but its location-scoped MCP registry never completed;
    # leave the pending marker so the next start retries the reconciliation.
    mkdir -p "$(devcontainer_state_dir)"
    : > "$restart_marker" 2>/dev/null || true
    printf '[devcontainer] ERROR: OpenCode did not register all managed MCP servers after restart.\n' >&2
    return 1
  fi
  rm -f "$restart_marker" 2>/dev/null || true
}

stamp_dir="$(devcontainer_state_dir)"
mkdir -p "$stamp_dir"

# A previous start that failed to restart an active OpenCode service must be
# retried even when the files have not changed since.
opencode_restart_pending=0
if [ -f "$stamp_dir/opencode-restart.pending" ]; then
  opencode_restart_pending=1
fi

opencode_config_before="$(devcontainer_opencode_config_fingerprint)"
devcontainer_sync_mcp_configs "$script_dir"
opencode_config_after="$(devcontainer_opencode_config_fingerprint)"
if [ "$env_changed" -eq 1 ] || [ "$opencode_config_before" != "$opencode_config_after" ] \
  || [ "$opencode_restart_pending" -eq 1 ]; then
  devcontainer_refresh_opencode_service_if_needed 1
fi

# Background CLI refresh, guarded by a lock so overlapping starts coalesce.
# A failed refresh is recorded for diagnostics; the foreground readiness repair
# on the next start will retry it rather than treating an old stamp as success.
devcontainer_assert_no_symlink_path "$stamp_dir/refresh.lock"
(
  if flock -n 9; then
    if ! devcontainer_refresh_clis_if_stale >>"$stamp_dir/refresh.log" 2>&1; then
      printf '[devcontainer] background CLI refresh failed; see %s\n' "$stamp_dir/refresh.log" >&2
      : > "$stamp_dir/refresh.failed"
      exit 1
    fi
    rm -f "$stamp_dir/refresh.failed"
  fi
) 9>"$stamp_dir/refresh.lock" &

echo "[devcontainer] ready. (MCP configs synced; CLI refresh: background/daily.)"
