#!/usr/bin/env bash
# postStartCommand: runs on every container start. Kept fast (<2s foreground).
# Syncs env + MCP configs, then refreshes CLIs in the background at most once
# per day (set DEVCONTAINER_CLI_REFRESH=always in .env.local to force).
set -uo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/env.sh
source "$script_dir/lib/env.sh"
# shellcheck source=lib/install-clis.sh
source "$script_dir/lib/install-clis.sh"
# shellcheck source=lib/mcp-config.sh
source "$script_dir/lib/mcp-config.sh"

devcontainer_fix_ownership

# Persist resolved credentials for interactive shells (600, container-only).
env_file="$HOME/.container-env.sh"
{
  printf '# generated by post-start.sh from .env.local / .env / inherited env\n'
  for name in GITHUB_PERSONAL_ACCESS_TOKEN Z_AI_API_KEY Z_AI_MODE GH_TOKEN OPENAI_API_KEY ANTHROPIC_API_KEY OPENROUTER_API_KEY CONTEXT7_API_KEY; do
    value="${!name:-}"
    if [ -n "$value" ]; then
      printf 'export %s=%q\n' "$name" "$value"
    fi
  done
} > "$env_file"
chmod 600 "$env_file" 2>/dev/null || true
for rc in "$HOME/.bashrc" "$HOME/.profile"; do
  if [ -f "$rc" ] && ! grep -q '.container-env.sh' "$rc"; then
    printf '\n[ -f "$HOME/.container-env.sh" ] && . "$HOME/.container-env.sh"\n' >> "$rc"
  fi
done

devcontainer_sync_mcp_configs "$script_dir"

# Background CLI refresh, guarded by a lock so overlapping starts coalesce.
stamp_dir="$HOME/.cache/signal-fish-devcontainer"
mkdir -p "$stamp_dir"
(
  if flock -n 9; then
    devcontainer_refresh_clis_if_stale >>"$stamp_dir/refresh.log" 2>&1
  fi
) 9>"$stamp_dir/refresh.lock" &

echo "[devcontainer] ready. (MCP configs synced; CLI refresh: background/daily.)"
