#!/usr/bin/env bash
# Install and launch isolated AI backends (Z.ai subscription, OpenRouter)
# without changing the native `claude` or `codex` defaults.
#
# Launchers installed by `install`:
#   claude-zai           Claude Code on the Z.ai GLM Coding Plan
#   claude-openrouter    Claude Code on OpenRouter's Anthropic-compatible API
#   codex-zai            Codex CLI on Z.ai's Responses endpoint
#   codex-openrouter     Codex CLI on OpenRouter's Responses endpoint
#
# Keys resolve from the environment first, then the repository's .env.local
# (AI_BACKENDS_ENV_LOCAL overrides the path). Key values never appear in
# argv, in the codex config, or in any written file.
#
# Pattern proven in Ambiguous-Interactive/qora-redux (.devcontainer/ai-backends.sh).

set -euo pipefail

readonly MARKER_CORE="signal-fish-devcontainer managed AI backends"
readonly MANAGED_BEGIN="# >>> ${MARKER_CORE} (regenerated by ai-backends.sh install; do not edit) <<<"
readonly MANAGED_END="# <<< ${MARKER_CORE} <<<"
readonly ZAI_RESPONSES_URL="https://api.z.ai/api/v1"
readonly ZAI_ANTHROPIC_URL="https://api.z.ai/api/anthropic"
readonly OPENROUTER_RESPONSES_URL="https://openrouter.ai/api/v1"
readonly OPENROUTER_ANTHROPIC_URL="https://openrouter.ai/api"
readonly ZAI_CATALOG_FILE="zai-models.json"

die() {
  printf '[ai-backends] ERROR: %s\n' "$*" >&2
  exit 1
}

resolve_action() {
  local invoked_as
  invoked_as="$(basename "$0")"
  case "${invoked_as}" in
    claude-zai | claude-openrouter | codex-zai | codex-openrouter)
      printf '%s\n' "${invoked_as}"
      ;;
    *)
      printf '%s\n' "${1:-help}"
      ;;
  esac
}

# Read one KEY=VALUE from a .env.local file without executing it: comments,
# an optional export prefix, whitespace around the equals sign, surrounding
# quotes, an inline " #..." comment outside quotes, and CRLF endings are all
# handled; the last assignment of a duplicated key wins; nothing is ever
# expanded or sourced.
read_env_local_value() {
  local file="$1" name="$2" line key value taken
  [ -f "${file}" ] || return 1
  taken=""
  while IFS= read -r line || [ -n "${line}" ]; do
    line="${line%$'\r'}"
    line="${line#"${line%%[![:space:]]*}"}"
    case "${line}" in
      '' | \#*) continue ;;
      export\ *) line="${line#export}"; line="${line#"${line%%[![:space:]]*}"}" ;;
    esac
    case "${line}" in
      *=*) ;;
      *) continue ;;
    esac
    key="${line%%=*}"
    key="${key%"${key##*[![:space:]]}"}"
    [ "${key}" = "${name}" ] || continue
    value="${line#*=}"
    value="${value#"${value%%[![:space:]]*}"}"
    value="${value%"${value##*[![:space:]]}"}"
    case "${value}" in
      \"*\"*)
        value="${value#\"}"
        value="${value%%\"*}"
        taken="${value}"
        ;;
      \'*\'*)
        value="${value#\'}"
        value="${value%%\'*}"
        taken="${value}"
        ;;
      \"* | \'*)
        # A quote opened but never closed: skip the line rather than hand a
        # raw opening quote to a launcher as a key.
        ;;
      *)
        case "${value}" in
          *' #'*) value="${value%%' #'*}" ;;
        esac
        value="${value%"${value##*[![:space:]]}"}"
        taken="${value}"
        ;;
    esac
  done <"${file}"
  [ -n "${taken}" ] || return 1
  printf '%s' "${taken}"
}

# The repository's .env.local: walk up from the script's real location first
# (a symlinked launcher resolves into the checkout), then from the caller's
# directory, which is the only trail a copied launcher on a no-symlink
# filesystem leaves. AI_BACKENDS_ENV_LOCAL always wins.
find_env_local() {
  local candidate dir base
  for base in "$(dirname "$(realpath "${BASH_SOURCE[0]}")")" "${PWD}"; do
    dir="$(cd "${base}" && pwd -P)"
    while [ "${dir}" != "/" ]; do
      candidate="${dir}/.env.local"
      if [ -f "${candidate}" ]; then
        printf '%s' "${candidate}"
        return 0
      fi
      dir="$(dirname "${dir}")"
    done
  done
  return 1
}

resolve_zai_key() {
  local env_local key
  if [ -n "${ZAI_API_KEY:-}" ]; then
    printf '%s' "${ZAI_API_KEY}"
    return
  fi
  if [ -n "${Z_AI_API_KEY:-}" ]; then
    printf '%s' "${Z_AI_API_KEY}"
    return
  fi
  if [ -n "${AI_BACKENDS_ENV_LOCAL:-}" ]; then
    env_local="${AI_BACKENDS_ENV_LOCAL}"
  elif ! env_local="$(find_env_local)"; then
    die "Set ZAI_API_KEY (or Z_AI_API_KEY) before launching a Z.ai backend."
  fi
  if key="$(read_env_local_value "${env_local}" ZAI_API_KEY)" && [ -n "${key}" ]; then
    printf '%s' "${key}"
    return
  fi
  if key="$(read_env_local_value "${env_local}" Z_AI_API_KEY)" && [ -n "${key}" ]; then
    printf '%s' "${key}"
    return
  fi
  die "Set ZAI_API_KEY (or Z_AI_API_KEY) before launching a Z.ai backend."
}

resolve_openrouter_key() {
  local env_local key
  if [ -n "${OPENROUTER_API_KEY:-}" ]; then
    printf '%s' "${OPENROUTER_API_KEY}"
    return
  fi
  if [ -n "${AI_BACKENDS_ENV_LOCAL:-}" ]; then
    env_local="${AI_BACKENDS_ENV_LOCAL}"
  elif ! env_local="$(find_env_local)"; then
    die "Set OPENROUTER_API_KEY before launching an OpenRouter backend."
  fi
  if key="$(read_env_local_value "${env_local}" OPENROUTER_API_KEY)" && [ -n "${key}" ]; then
    printf '%s' "${key}"
    return
  fi
  die "Set OPENROUTER_API_KEY before launching an OpenRouter backend."
}

codex_home_dir() {
  printf '%s' "${CODEX_HOME:-${HOME}/.codex}"
}

# Model metadata for Z.ai's Codex Responses integration (contract proven in
# qora-redux): without a catalog, glm models fall back to unknown-model
# metadata and wrong context windows.
write_zai_catalog() {
  local codex_home catalog_tmp
  codex_home="$(codex_home_dir)"
  mkdir -p "${codex_home}"
  chmod 700 "${codex_home}" 2>/dev/null || true
  catalog_tmp="$(mktemp "${codex_home}/.${ZAI_CATALOG_FILE}.XXXXXX")"
  cat >"${catalog_tmp}" <<'JSON'
{
  "models": [
    {
      "slug": "glm-5.3",
      "display_name": "glm-5.3",
      "description": "Z.ai flagship coding model",
      "default_reasoning_level": "max",
      "supported_reasoning_levels": [
        { "effort": "low", "description": "Light reasoning" },
        { "effort": "high", "description": "Enhanced reasoning" },
        { "effort": "max", "description": "Deep reasoning" }
      ],
      "shell_type": "shell_command",
      "visibility": "list",
      "supported_in_api": true,
      "priority": 0,
      "base_instructions": "",
      "supports_reasoning_summaries": true,
      "default_reasoning_summary": "none",
      "support_verbosity": false,
      "apply_patch_tool_type": "freeform",
      "truncation_policy": { "mode": "bytes", "limit": 10000 },
      "context_window": 1048576,
      "max_context_window": 1048576,
      "effective_context_window_percent": 95,
      "supports_parallel_tool_calls": true,
      "experimental_supported_tools": [],
      "input_modalities": ["text"]
    }
  ]
}
JSON
  chmod 600 "${catalog_tmp}" 2>/dev/null || true
  mv "${catalog_tmp}" "${codex_home}/${ZAI_CATALOG_FILE}"
}

# Managed provider/profile tables in ~/.codex/config.toml. Top-level keys
# (model_provider/model) are deliberately NOT set: plain `codex` keeps its
# native backend; provider selection happens via --profile/--config at launch.
write_codex_managed_block() {
  local codex_home file tmp
  codex_home="$(codex_home_dir)"
  file="${codex_home}/config.toml"
  mkdir -p "${codex_home}"
  [ -f "$file" ] || : > "$file"

  tmp="$(mktemp "${codex_home}/.config.XXXXXX")"
  awk -v core="${MARKER_CORE}" -v begin="${MANAGED_BEGIN}" -v end="${MANAGED_END}" '
    $0 == begin { inblock = 1; next }
    $0 == end   { inblock = 0; next }
    index($0, core) { next }
    inblock { next }
    { print }
  ' "$file" > "$tmp"
  printf '%s' "$(cat "$tmp")" > "$file"
  rm -f "$tmp"
  if [ -s "$file" ]; then
    printf '\n' >> "$file"
  fi

  {
    printf '%s\n' "${MANAGED_BEGIN}"
    cat <<'TOML'
# Z.ai (GLM Coding Plan) - Responses endpoint, key via environment.
[model_providers.zai]
name = "Z.ai"
base_url = "https://api.z.ai/api/v1"
env_key = "ZAI_API_KEY"
wire_api = "responses"
request_max_retries = 4
stream_max_retries = 5
stream_idle_timeout_ms = 300000

# OpenRouter - Responses endpoint, key via environment. Command-based auth
# (not env_key) is what makes Codex fetch OpenRouter's model catalog.
[model_providers.openrouter]
name = "openrouter"
base_url = "https://openrouter.ai/api/v1"
wire_api = "responses"
request_max_retries = 4
stream_max_retries = 5
stream_idle_timeout_ms = 300000

[model_providers.openrouter.auth]
command = "sh"
args = ["-c", "echo $OPENROUTER_API_KEY"]

[profiles.zai]
model_provider = "zai"
model = "glm-5.3"
model_reasoning_effort = "max"

[profiles.openrouter]
model_provider = "openrouter"
model = "openrouter/auto"

# Keep provider keys out of tool subprocess environments.
[shell_environment_policy]
filters = { ZAI_API_KEY = "exclude", Z_AI_API_KEY = "exclude", OPENROUTER_API_KEY = "exclude" }
TOML
    printf '%s\n' "${MANAGED_END}"
  } >> "$file"
  chmod 600 "$file" 2>/dev/null || true
}

codex_managed_block_present() {
  grep -qF "${MANAGED_BEGIN}" "$(codex_home_dir)/config.toml" 2>/dev/null
}

install_launchers() {
  local bin_dir codex_command launcher script_path target
  if [ -n "${AI_BACKENDS_BIN_DIR:-}" ]; then
    bin_dir="${AI_BACKENDS_BIN_DIR}"
  elif case ":${PATH}:" in *":${HOME}/.local/bin:"*) true ;; *) false ;; esac; then
    bin_dir="${HOME}/.local/bin"
  else
    codex_command="$(command -v codex || true)"
    if [ -n "${codex_command}" ] && [ -w "$(dirname "${codex_command}")" ]; then
      # The npm-global bin directory is on PATH in this image, so the
      # launchers become immediately callable next to codex/claude.
      bin_dir="$(dirname "${codex_command}")"
    else
      bin_dir="${HOME}/.local/bin"
      mkdir -p "${bin_dir}"
    fi
  fi
  script_path="$(realpath "${BASH_SOURCE[0]}")"
  chmod 0755 "${script_path}" 2>/dev/null || true
  mkdir -p "${bin_dir}"

  for launcher in claude-zai claude-openrouter codex-zai codex-openrouter; do
    target="${bin_dir}/${launcher}"
    # A copy this installer made carries the script's own header, however
    # stale; anything else under our launcher names is someone else's binary
    # and is refused.
    if [ -e "${target}" ] && [ ! -L "${target}" ] && ! grep -q "isolated AI backends" "${target}" 2>/dev/null; then
      die "Refusing to replace non-symlink launcher: ${target}"
    fi
    if ln -sfn "${script_path}" "${target}" 2>/dev/null && [ -L "${target}" ]; then
      continue
    fi
    # MSYS `ln -s` copies instead of linking, and some filesystems refuse
    # symlinks outright; a copy serves the same contract.
    cp -f "${script_path}" "${target}"
    chmod 0755 "${target}" 2>/dev/null || true
  done
}

install_backend_support() {
  write_zai_catalog
  write_codex_managed_block
  install_launchers
  printf '[ai-backends] Installed claude-zai, claude-openrouter, codex-zai, codex-openrouter launchers.\n'
}

container_mode_detected() {
  local container_mode="${AI_BACKENDS_CONTAINER_MODE:-auto}"
  case "${container_mode}" in
    auto)
      if [ -f /.dockerenv ] || [ -f /run/.containerenv ]; then
        container_mode=yes
      else
        container_mode=no
      fi
      ;;
    yes | no) ;;
    *) die "AI_BACKENDS_CONTAINER_MODE must be auto, yes, or no." ;;
  esac
  printf '%s' "${container_mode}"
}

# Shared Claude Code backend launcher. $1 = backend name (zai|openrouter).
launch_claude_backend() {
  local backend="$1"
  local config_dir timeout_ms zai_key or_key container_mode subprocess_scrub
  local -a claude_args=()
  command -v claude >/dev/null 2>&1 || die "claude is not installed."

  if [ "${backend}" = "zai" ]; then
    zai_key="$(resolve_zai_key)"
    config_dir="${CLAUDE_ZAI_CONFIG_DIR:-${HOME}/.claude-zai}"
    timeout_ms="${ZAI_API_TIMEOUT_MS:-300000}"
  else
    or_key="$(resolve_openrouter_key)"
    config_dir="${CLAUDE_OPENROUTER_CONFIG_DIR:-${HOME}/.claude-openrouter}"
    timeout_ms="${OPENROUTER_API_TIMEOUT_MS:-600000}"
  fi
  case "${timeout_ms}" in
    '' | *[!0-9]*) die "API timeout must be a positive integer (ms)." ;;
    0) die "API timeout must be greater than zero." ;;
  esac
  mkdir -p "${config_dir}"
  chmod 700 "${config_dir}" 2>/dev/null || true

  container_mode="$(container_mode_detected)"

  subprocess_scrub="${CLAUDE_SUBPROCESS_ENV_SCRUB:-auto}"
  case "${subprocess_scrub}" in
    auto)
      if [ "${container_mode}" = "yes" ]; then
        # The devcontainer is already the isolation boundary. Claude's
        # additional Linux scrub sandbox needs CLONE_NEWUSER and mount
        # operations that Docker's default profiles deny.
        subprocess_scrub=0
      else
        subprocess_scrub=1
      fi
      ;;
    0 | 1) ;;
    *) die "CLAUDE_SUBPROCESS_ENV_SCRUB must be auto, 0, or 1." ;;
  esac

  if [ "$(uname -s)" = "Linux" ] && [ "${subprocess_scrub}" = "1" ]; then
    command -v bwrap >/dev/null 2>&1 \
      || die "bubblewrap is required for Claude subprocess isolation; install bubblewrap and socat."
    command -v socat >/dev/null 2>&1 \
      || die "socat is required for Claude sandbox networking; install bubblewrap and socat."
    bwrap --unshare-user --ro-bind / / --bind /proc /proc --dev /dev true \
      || die "Claude subprocess isolation cannot create its nested sandbox. Set CLAUDE_SUBPROCESS_ENV_SCRUB=0 to rely on the outer devcontainer boundary."
  fi

  if [ "${container_mode}" = "yes" ]; then
    # The outer devcontainer is the primary isolation boundary; keep the
    # inner sandbox off unless the caller explicitly opts in via scrub mode.
    claude_args+=(--settings '{"sandbox":{"enabled":false,"enableWeakerNestedSandbox":true}}')
  fi

  # Isolate from every ambient provider routing variable so project settings
  # and inherited environments cannot override the managed backend.
  unset ANTHROPIC_API_KEY \
    ANTHROPIC_MODEL \
    ANTHROPIC_DEFAULT_MODEL \
    ANTHROPIC_DEFAULT_FABLE_MODEL \
    ANTHROPIC_DEFAULT_HAIKU_MODEL \
    ANTHROPIC_DEFAULT_SONNET_MODEL \
    ANTHROPIC_DEFAULT_OPUS_MODEL \
    ANTHROPIC_SMALL_FAST_MODEL \
    CLAUDE_CODE_PROVIDER_MANAGED_BY_HOST \
    CLAUDE_CODE_USE_ANTHROPIC_AWS \
    CLAUDE_CODE_USE_BEDROCK \
    CLAUDE_CODE_USE_VERTEX \
    CLAUDE_CODE_USE_FOUNDRY \
    CLAUDE_CODE_USE_MANTLE \
    CLAUDE_CODE_USE_GATEWAY \
    ZAI_API_KEY Z_AI_API_KEY

  if [ "${backend}" = "zai" ]; then
    export ANTHROPIC_AUTH_TOKEN="${zai_key}"
    export ANTHROPIC_BASE_URL="${ZAI_ANTHROPIC_URL}"
    export ANTHROPIC_DEFAULT_HAIKU_MODEL="${CLAUDE_ZAI_HAIKU_MODEL:-glm-5.3-flash[1m]}"
    export ANTHROPIC_DEFAULT_SONNET_MODEL="${CLAUDE_ZAI_SONNET_MODEL:-glm-5.3[1m]}"
    export ANTHROPIC_DEFAULT_OPUS_MODEL="${CLAUDE_ZAI_OPUS_MODEL:-glm-5.3[1m]}"
    export CLAUDE_CODE_AUTO_COMPACT_WINDOW=1000000
    export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1
  else
    # OpenRouter's Anthropic-compatible endpoint authenticates with a bearer
    # token; ANTHROPIC_API_KEY must be explicitly empty to prevent fallback
    # to direct-Anthropic auth (per OpenRouter's integration guide).
    export ANTHROPIC_AUTH_TOKEN="${or_key}"
    export ANTHROPIC_BASE_URL="${OPENROUTER_ANTHROPIC_URL}"
    export ANTHROPIC_API_KEY=""
    export ANTHROPIC_DEFAULT_FABLE_MODEL="${CLAUDE_OPENROUTER_FABLE_MODEL:-~anthropic/claude-fable-latest[1m]}"
    export ANTHROPIC_DEFAULT_OPUS_MODEL="${CLAUDE_OPENROUTER_OPUS_MODEL:-~anthropic/claude-opus-latest[1m]}"
    export ANTHROPIC_DEFAULT_SONNET_MODEL="${CLAUDE_OPENROUTER_SONNET_MODEL:-~anthropic/claude-sonnet-latest[1m]}"
    export ANTHROPIC_DEFAULT_HAIKU_MODEL="${CLAUDE_OPENROUTER_HAIKU_MODEL:-~anthropic/claude-haiku-latest}"
    export CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY=1
    export CLAUDE_CODE_SKIP_FAST_MODE_ORG_CHECK=1
  fi

  export API_TIMEOUT_MS="${timeout_ms}"
  export CLAUDE_CODE_PROVIDER_MANAGED_BY_HOST=1
  export CLAUDE_CODE_SUBPROCESS_ENV_SCRUB="${subprocess_scrub}"
  export CLAUDE_CONFIG_DIR="${config_dir}"
  exec claude "${claude_args[@]}" "$@"
}

launch_codex_backend() {
  local backend="$1"
  local codex_home catalog_file model reasoning_effort zai_key
  command -v codex >/dev/null 2>&1 || die "codex is not installed."

  codex_home="$(codex_home_dir)"
  if ! codex_managed_block_present; then
    write_codex_managed_block
    write_zai_catalog
  fi

  if [ "${backend}" = "zai" ]; then
    zai_key="$(resolve_zai_key)"
    export ZAI_API_KEY="${zai_key}"
    catalog_file="${codex_home}/${ZAI_CATALOG_FILE}"
    [ -f "${catalog_file}" ] || write_zai_catalog
    model="${CODEX_ZAI_MODEL:-glm-5.3}"
    reasoning_effort="${CODEX_ZAI_REASONING_EFFORT:-max}"
    case "${reasoning_effort}" in
      low | high | max) ;;
      *) die "CODEX_ZAI_REASONING_EFFORT must be low, high, or max." ;;
    esac
    exec codex \
      --profile zai \
      --model "${model}" \
      --config 'model_provider="zai"' \
      --config "model_reasoning_effort=\"${reasoning_effort}\"" \
      --config "model_catalog_json=\"${catalog_file}\"" \
      "$@"
  else
    local or_key
    or_key="$(resolve_openrouter_key)"
    export OPENROUTER_API_KEY="${or_key}"
    model="${CODEX_OPENROUTER_MODEL:-openrouter/auto}"
    exec codex \
      --profile openrouter \
      --model "${model}" \
      --config 'model_provider="openrouter"' \
      "$@"
  fi
}

print_help() {
  cat <<'HELP'
Usage:
  bash .devcontainer/ai-backends.sh install
  claude-zai [claude arguments...]
  claude-openrouter [claude arguments...]
  codex-zai [codex arguments...]
  codex-openrouter [codex arguments...]

The ordinary `claude` and `codex` commands retain their native backends.

Keys (environment wins, then the repository's .env.local):
  ZAI_API_KEY (or Z_AI_API_KEY)   Z.ai GLM Coding Plan
  OPENROUTER_API_KEY              OpenRouter

Optional overrides:
  CODEX_ZAI_MODEL, CODEX_ZAI_REASONING_EFFORT (low|high|max)
  CODEX_OPENROUTER_MODEL (OpenRouter slug, e.g. ~anthropic/claude-sonnet-latest)
  ZAI_API_TIMEOUT_MS, OPENROUTER_API_TIMEOUT_MS
  CLAUDE_ZAI_CONFIG_DIR, CLAUDE_OPENROUTER_CONFIG_DIR
  CLAUDE_ZAI_HAIKU_MODEL, CLAUDE_ZAI_SONNET_MODEL, CLAUDE_ZAI_OPUS_MODEL
  CLAUDE_OPENROUTER_FABLE_MODEL, CLAUDE_OPENROUTER_OPUS_MODEL,
  CLAUDE_OPENROUTER_SONNET_MODEL, CLAUDE_OPENROUTER_HAIKU_MODEL
  AI_BACKENDS_CONTAINER_MODE (auto|yes|no)
  CLAUDE_SUBPROCESS_ENV_SCRUB (auto|0|1)
  AI_BACKENDS_ENV_LOCAL (path to an alternate .env.local)
  AI_BACKENDS_BIN_DIR (launcher install directory)
HELP
}

action="$(resolve_action "${1:-}")"
if [ "$(basename "$0")" = "ai-backends.sh" ] && [ "$#" -gt 0 ]; then
  shift
fi

case "${action}" in
  install) install_backend_support ;;
  claude-zai) launch_claude_backend zai "$@" ;;
  claude-openrouter) launch_claude_backend openrouter "$@" ;;
  codex-zai) launch_codex_backend zai "$@" ;;
  codex-openrouter) launch_codex_backend openrouter "$@" ;;
  help | -h | --help) print_help ;;
  *) die "Unknown action: ${action}" ;;
esac
