<#
.SYNOPSIS
    Enforces the two legal comment forms in C# sources (src/ and tests/).

.DESCRIPTION
    Issue #20 policy: a comment spanning more than one line is ONE
    `/* ... */` block (never a stack of `//` lines), and a single-line
    comment is `// text` (never a one-line `/* ... */`). `///` XML doc
    comments are API documentation and are untouched. Runs of tool
    directives (cspell, ReSharper, Justification, auto-generated markers)
    are exempt: each line is read by a tool, not a human.

    Depth comes from indentation rather than brace counting, which
    CSharpier guarantees: a namespace body is indented four, a type body
    eight. So a `//` run indented eight or more is inside a type or member.
    Trailing comments on a code line are single comments and never join a
    run. Comment detection is string-aware (`//` inside a literal is not a
    comment; raw `"""`, verbatim `@"`, and interpolated strings do not leak).

    Run standalone, from CI (dotnet.yml), or from the pre-commit hook
    (which passes only staged paths).

.PARAMETER RepoRoot
    Repository root. Defaults to the parent of the scripts directory.

.PARAMETER Paths
    Optional repo-relative (or absolute) file paths to check. When omitted,
    every *.cs file under src/ and tests/ is checked.

.EXAMPLE
    pwsh -NoProfile -File scripts/lint-comment-form.ps1
#>
[CmdletBinding()]
param(
    [string]$RepoRoot,
    [string[]]$Paths
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

if (-not $RepoRoot) {
    $RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
}

function Resolve-TargetPath {
    param([string]$Path)
    if ([System.IO.Path]::IsPathRooted($Path)) { return $Path }
    return Join-Path $RepoRoot ($Path -replace '/', [System.IO.Path]::DirectorySeparatorChar)
}

if ($Paths -and @($Paths).Count -gt 0) {
    $targets = [string[]]@($Paths | ForEach-Object { Resolve-TargetPath -Path $_ } |
        Where-Object { $_.EndsWith('.cs', [System.StringComparison]::OrdinalIgnoreCase) })
}
else {
    $targets = [string[]]@('src', 'tests' | ForEach-Object { Join-Path $RepoRoot $_ } |
        Where-Object { Test-Path -LiteralPath $_ } |
        ForEach-Object { Get-ChildItem -LiteralPath $_ -Recurse -File -Include '*.cs' } |
        Where-Object { $_.FullName -notmatch '[\\/](bin|obj)[\\/]' } |
        ForEach-Object { $_.FullName })
}
[System.Array]::Sort($targets, [System.StringComparer]::Ordinal)

if ($targets.Count -eq 0) {
    if ($Paths -and @($Paths).Count -gt 0) {
        exit 0
    }
    Write-Host 'lint-comment-form FAILED: no *.cs found under src/ or tests/.'
    exit 1
}

# A run made only of directives is not prose and has no block form: a tool
# reads each line.
$directivePattern = '^(//\s*)(cspell:|ReSharper|resharper|Justification:|<auto-generated)'

function Get-LineStarts {
    param([string]$Text)
    $starts = New-Object 'System.Collections.Generic.List[int]'
    $starts.Add(0) | Out-Null
    for ($i = 0; $i -lt $Text.Length; $i++) {
        if ($Text[$i] -eq "`n") { $starts.Add($i + 1) | Out-Null }
    }
    return ,$starts
}

function Get-CSharpComments {
    # Returns comment ranges as @{ Start; End; Kind } where Kind is
    # LineComment, XmlDoc, or BlockComment. String literals (regular,
    # verbatim, raw, interpolated) never leak comment characters.
    param([string]$Text)

    $ranges = New-Object 'System.Collections.Generic.List[object]'
    $len = $Text.Length
    $i = 0
    while ($i -lt $len) {
        $c = $Text[$i]

        if ($c -eq '/' -and ($i + 1) -lt $len) {
            $next = $Text[$i + 1]
            if ($next -eq '/') {
                $start = $i
                $kind = 'LineComment'
                if (($i + 2) -lt $len -and $Text[$i + 2] -eq '/') { $kind = 'XmlDoc' }
                while ($i -lt $len -and $Text[$i] -ne "`n") { $i++ }
                $ranges.Add(@{ Start = $start; End = $i; Kind = $kind })
                continue
            }
            if ($next -eq '*') {
                $start = $i
                $i += 2
                while ($i -lt $len - 1 -and ($Text[$i] -ne '*' -or $Text[$i + 1] -ne '/')) { $i++ }
                $i = [Math]::Min($i + 2, $len)
                $ranges.Add(@{ Start = $start; End = $i; Kind = 'BlockComment' })
                continue
            }
        }

        if ($c -eq '"' -and ($i + 2) -lt $len -and $Text[$i + 1] -eq '"' -and $Text[$i + 2] -eq '"') {
            # Raw string: the opening run length (3+) is the closing length.
            $quoteCount = 0
            $j = $i
            while ($j -lt $len -and $Text[$j] -eq '"') { $quoteCount++; $j++ }
            $i = $j
            while ($i -lt $len) {
                if ($Text[$i] -eq '"') {
                    $endCount = 0
                    $k = $i
                    while ($k -lt $len -and $Text[$k] -eq '"') { $endCount++; $k++ }
                    if ($endCount -ge $quoteCount) { $i = $k; break }
                    $i = $k
                    continue
                }
                $i++
            }
            continue
        }

        if (($c -eq '$' -or $c -eq '@') -and ($i + 1) -lt $len -and $Text[$i + 1] -eq '"') {
            # Interpolated ($") or verbatim (@" or $@") string; only verbatim
            # and raw-interpolated forms span lines, and "" is an escaped
            # quote inside them. Single-line forms end at the next quote or
            # newline either way; escapes other than "" do not apply.
            $i += 2
            while ($i -lt $len) {
                if ($Text[$i] -eq '"') {
                    if (($i + 1) -lt $len -and $Text[$i + 1] -eq '"') { $i += 2; continue }
                    $i++
                    break
                }
                if ($Text[$i] -eq "`n" -and $Text[$i - 1] -ne '@') {
                    # A regular interpolated string cannot span lines; stop so
                    # code after a broken literal is still scanned.
                    break
                }
                $i++
            }
            continue
        }

        if ($c -eq '"') {
            $i++
            while ($i -lt $len) {
                if ($Text[$i] -eq '\' -and ($i + 1) -lt $len) { $i += 2; continue }
                if ($Text[$i] -eq '"') { $i++; break }
                if ($Text[$i] -eq "`n") { break }
                $i++
            }
            continue
        }

        if ($c -eq "'") {
            $i++
            while ($i -lt $len) {
                if ($Text[$i] -eq '\' -and ($i + 1) -lt $len) { $i += 2; continue }
                if ($Text[$i] -eq "'") { $i++; break }
                if ($Text[$i] -eq "`n") { break }
                $i++
            }
            continue
        }

        $i++
    }
    return ,$ranges
}

$violations = New-Object 'System.Collections.Generic.List[string]'
$checkedCount = 0

foreach ($target in $targets) {
    if (-not (Test-Path -LiteralPath $target)) {
        $violations.Add("path not found: $target")
        continue
    }

    $fullPath = [System.IO.Path]::GetFullPath($target)
    $rootPath = [System.IO.Path]::GetFullPath($RepoRoot).TrimEnd('\', '/')
    if ($fullPath.StartsWith($rootPath, [System.StringComparison]::OrdinalIgnoreCase)) {
        $relative = $fullPath.Substring($rootPath.Length + 1)
    }
    else {
        $relative = $fullPath
    }
    $relative = $relative -replace '\\', '/'
    $checkedCount++

    $text = [System.IO.File]::ReadAllText($target)
    $lineStarts = Get-LineStarts -Text $text

    $lineOf = {
        param([int]$Offset)
        $lo = 0
        $hi = $lineStarts.Count - 1
        while ($lo -lt $hi) {
            $mid = [Math]::Floor(($lo + $hi + 1) / 2)
            if ($lineStarts[$mid] -le $Offset) { $lo = $mid } else { $hi = $mid - 1 }
        }
        return $lo
    }

    # Standalone line comments (a trailing comment after code is one comment
    # on that line and never joins a run).
    $standalone = New-Object 'System.Collections.Generic.List[object]'
    $searchFrom = 0
    foreach ($range in (Get-CSharpComments -Text $text)) {
        if ($range.Kind -eq 'BlockComment') {
            $startLine = & $lineOf $range.Start
            $endLine = & $lineOf ([Math]::Max($range.End - 1, $range.Start))
            if ($startLine -eq $endLine) {
                $violations.Add(
                    "$relative($($startLine + 1)): one-line /* ... */ comment - single-line form is `// text`.")
            }
            continue
        }
        if ($range.Kind -ne 'LineComment') { continue }

        while (($searchFrom + 1) -lt $lineStarts.Count -and $lineStarts[$searchFrom + 1] -le $range.Start) {
            $searchFrom++
        }
        $lineStart = $lineStarts[$searchFrom]
        $prefix = $text.Substring($lineStart, $range.Start - $lineStart)
        if ($prefix.Trim().Length -gt 0) { continue }
        $standalone.Add(@{
            Line   = $searchFrom + 1
            Indent = $prefix.Length
            Text   = $text.Substring($range.Start, $range.End - $range.Start).TrimEnd("`r")
        }) | Out-Null
    }

    $runStart = 0
    while ($runStart -lt $standalone.Count) {
        $runEnd = $runStart
        while (($runEnd + 1) -lt $standalone.Count -and
            $standalone[$runEnd + 1].Line -eq ($standalone[$runEnd].Line + 1)) {
            $runEnd++
        }

        $length = $runEnd - $runStart + 1
        if ($length -ge 2) {
            $insideType = $true
            $allDirectives = $true
            for ($index = $runStart; $index -le $runEnd; $index++) {
                if ($standalone[$index].Indent -lt 8) { $insideType = $false }
                if ($standalone[$index].Text -notmatch $directivePattern) { $allDirectives = $false }
            }
            if ($insideType -and -not $allDirectives) {
                $first = $standalone[$runStart].Text
                if ($first.Length -gt 70) { $first = $first.Substring(0, 70) }
                $violations.Add(
                    "$relative($($standalone[$runStart].Line)): $length-line `//` run - write it as ONE " +
                    "``/* ... */`` block or delete it (first line: ``$first``).")
            }
        }
        $runStart = $runEnd + 1
    }
}

if ($violations.Count -gt 0) {
    foreach ($violation in $violations) {
        Write-Host "lint-comment-form: $violation"
    }
    Write-Host "lint-comment-form FAILED: checked $checkedCount file(s), $($violations.Count) violation(s)."
    exit 1
}
Write-Host "lint-comment-form passed: checked $checkedCount file(s), 0 violations."
exit 0
